# Article: Build Document Scanner using Computer Vision, OpenCV and Python

## Step 1: Read the photograph or image:

In [1]:
# import required libraries
import numpy as np
import cv2
import imutils

# parameter for image to scan/process
#args_image = "fuel_bill_to_scan.jpg"
args_image = "fuel_bill1.jpg"

# read the image
image = cv2.imread(args_image)
orig = image.copy()

# show the original image
cv2.imshow("Original Image", image)
cv2.waitKey(0) # press 0 to close all cv2 windows
cv2.destroyAllWindows()


## Step 2: Identify the edges:

In [12]:
# converted image from RGB to gray scale. This will remove any color noise
grayImage = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

# blur the image to remove high frequency noise 
# it helps in finding/detecting contour in gray image
grayImageBlur = cv2.blur(grayImage,(3,3)) 

# then we performed canny edge detection
edgedImage = cv2.Canny(grayImageBlur, 100, 300, 3)

# show the gray and edge-detected image
cv2.imshow("gray", grayImage)
cv2.imshow("grayBlur", grayImageBlur)
cv2.imshow("Edge Detected Image", edgedImage)
cv2.waitKey(0) # press 0 to close all cv2 windows
cv2.destroyAllWindows()


## Step 3: Detect edges in the image:

In [13]:
# find the contours in the edged image, sort area wise 
# keeping only the largest ones 
allContours = cv2.findContours(edgedImage.copy(), cv2.RETR_LIST, cv2.CHAIN_APPROX_SIMPLE)
allContours = imutils.grab_contours(allContours)

# descending sort contours area and keep top 1
allContours = sorted(allContours, key=cv2.contourArea, reverse=True)[:1]

# approximate the contour
perimeter = cv2.arcLength(allContours[0], True) 
ROIdimensions = cv2.approxPolyDP(allContours[0], 0.02*perimeter, True)
print("[INFO]: Got document. Coordinates are: ",ROIdimensions)

# show the contour on image
cv2.drawContours(image, [ROIdimensions], -1, (0,255,0), 2)
cv2.imshow("Contour Outline", image)
cv2.waitKey(0)
cv2.destroyAllWindows()

[INFO]: Got document. Coordinates are:  [[[126 107]]

 [[ 66 699]]

 [[514 698]]

 [[444 129]]]


## Step 4: Identify and extract document boundary/edges:

In [14]:
# reshape coordinates array
ROIdimensions = ROIdimensions.reshape(4,2)

# list to hold ROI coordinates
rect = np.zeros((4,2), dtype="float32")

# top left corner will have the smallest sum, 
# bottom right corner will have the largest sum
s = np.sum(ROIdimensions, axis=1)
rect[0] = ROIdimensions[np.argmin(s)]
rect[2] = ROIdimensions[np.argmax(s)]
print("[INFO]: Top-left corner:",rect[0]," bottom-right corner:",rect[2])

# top-right will have smallest difference
# botton left will have largest difference
diff = np.diff(ROIdimensions, axis=1)
rect[1] = ROIdimensions[np.argmin(diff)]
rect[3] = ROIdimensions[np.argmax(diff)]
print("[INFO]: Top-right corner:",rect[1]," bottom-left corner:",rect[3])

# display corner coordinates in order of 
# top-left, top-right, bottom-right, bottom-left
print("[INFO]: Coordinates are: ",rect)
(tl, tr, br, bl) = rect

# compute width of ROI
widthA = np.sqrt((tl[0] - tr[0])**2 + (tl[1] - tr[1])**2 )
widthB = np.sqrt((bl[0] - br[0])**2 + (bl[1] - br[1])**2 )
maxWidth = max(int(widthA), int(widthB))
print("[INFO]: Width of document is:",maxWidth)

# compute height of ROI
heightA = np.sqrt((tl[0] - bl[0])**2 + (tl[1] - bl[1])**2 )
heightB = np.sqrt((tr[0] - br[0])**2 + (tr[1] - br[1])**2 )
maxHeight = max(int(heightA), int(heightB))
print("[INFO]: Height of document is:",maxHeight)

[INFO]: Top-left corner: [126. 107.]  bottom-right corner: [514. 698.]
[INFO]: Top-right corner: [444. 129.]  bottom-left corner: [ 66. 699.]
[INFO]: Coordinates are:  [[126. 107.]
 [444. 129.]
 [514. 698.]
 [ 66. 699.]]
[INFO]: Width of document is: 448
[INFO]: Height of document is: 595


## Step 5: Apply perspective transform:

In [18]:
# Set of destinations points for "birds eye view"
# dimension of the new image
dst = np.array([
    [0,0],
    [maxWidth-1, 0],
    [maxWidth-1, maxHeight-1],
    [0, maxHeight-1]], dtype="float32")

# compute the perspective transform matrix and then apply it
transformMatrix = cv2.getPerspectiveTransform(rect, dst)

# transform ROI
scan = cv2.warpPerspective(orig, transformMatrix, (maxWidth, maxHeight))

# lets see the wraped document
cv2.imshow("Scaned",scan)
cv2.waitKey(0)
cv2.destroyAllWindows()

## Step 6: Final steps:

In [19]:
# convert to gray
scanGray = cv2.cvtColor(scan, cv2.COLOR_BGR2GRAY)

# display final image
cv2.imshow("scanGray", scanGray)
cv2.waitKey(0)
cv2.destroyAllWindows()


In [20]:
# convert to black/white with high contrast for documents
from skimage.filters import threshold_local 

# increase contrast incase its document
T = threshold_local(scanGray, 9, offset=8, method="gaussian")
scanBW = (scanGray > T).astype("uint8") * 255

cv2.imshow("warpedBW", scanBW)
cv2.waitKey(0)
cv2.destroyAllWindows()